name: "PR - Auto Assign"
on:
  pull_request:
    types: [opened, review_requested, ready_for_review]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/toshimaru/auto-author-assign
      - uses: toshimaru/auto-author-assign@v2.0.1
  fail_if_pull_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Fails in order to indicate that pull request needs to be marked as ready for review.
        run: exit 1
  assign-reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # https://github.com/kentaro-m/auto-assign-action
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: ".github/auto-assign-config.yml"
